/gazebo_ros_control:
  pid_gains:
    joint_a1:
      p: 16000
      d: 5
      i: 1
      i_clamp: 1
    joint_a2:
      p: 16000
      d: 5
      i: 1
      i_clamp: 1
    joint_a3:
      p: 16000
      d: 5
      i: 1
      i_clamp: 1
    joint_a4:
      p: 16000
      d: 5
      i: 1
      i_clamp: 1
    joint_a5:
      p: 16000
      d: 5
      i: 1
      i_clamp: 1
    joint_a6:
      p: 16000
      d: 5
      i: 1
      i_clamp: 1