# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 100
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_a1
    - joint_a2
    - joint_a3
    - joint_a4
    - joint_a5
    - joint_a6
  sim_control_mode: 0  # 0: position, 1: velocity
controller_list:
  - name: /joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints: [joint_a1, joint_a2, joint_a3, joint_a4, joint_a5, joint_a6]
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100
  joints:
    - joint_a1
    - joint_a2
    - joint_a3
    - joint_a4
    - joint_a5
    - joint_a6
joint_trajectory_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - joint_a1
    - joint_a2
    - joint_a3
    - joint_a4
    - joint_a5
    - joint_a6
  gains:
    joint_a1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_a2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_a3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_a4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_a5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_a6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1

